version: '3.6'

services:
  front:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  postgrest:
    image: postgrest/postgrest
    restart: unless-stopped
    environment:
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_URI=postgres://postgres@db/db

  db:
    image: timescale/timescaledb-postgis:latest-pg10
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/data
      - ./db:/var/lib/postgresql/data
      - ./aggregate_trips.sql:/aggregate_trips.sql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql